config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  %w(about help concept).each do |path|
    get path, to: "static_pages##{path}"
  end

  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}
  resources :users, only: :show
  
  resources :shops, only: [:index, :show] do
    resources :comments, only: [:create]
  end
  resources :comments, only: :destroy
  resources :likes, only: [:index, :create]
end

app/models/comment.rb
class Comment < ApplicationRecord
  include ImageUploader[:image]

  belongs_to :user, counter_cache: true
  belongs_to :shop, counter_cache: true

  validates :body, presence: true, length: {maximum: 500}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :user_signed_in?, only: [:create, :destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.shop_id = params[:shop_id]
    if @comment.save
      flash[:success] = "コメントが投稿されました。"
      redirect_back(fallback_location: root_url)
    else
      flash[:danger] = "投稿失敗しました。"
      redirect_back(fallback_location: root_url)
    end
  end
  
  def destroy
    current_user.comments.find_by(id: params[:id]).destroy
    flash[:success] = "コメントを削除しました。"
    redirect_back(fallback_location: root_url)
  end
  
  private
  
    def comment_params
      params.require(:comment).permit(:body, :image)
    end
end

app/views/comments/_new.html.slim
.row.w-75.d-block.mx-auto
  .col-md-6.col-md-offset-3.mx-auto.d-block
    - if user_signed_in?
      = form_for(current_user.comments.build, url: shop_comments_path(@shop.id)) do |f|
        .mt-5
          = f.label :body, "コメント"
          = f.text_area :body, class: "form-control pb-5 mb-3"
          = f.label :image_data , "画像　"
          = f.hidden_field :image, value: current_user.comments.build.cached_image_data
          = f.file_field :image, class:"rounded"
          = f.submit "コメントを投稿", class: "btn btn-info btn-lg my-3 w-100"
    - else
      = link_to "ログインしてコメントを投稿！", new_user_session_url, class: "btn btn-info btn-lg my-5 w-100"