config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  %w(about help concept).each do |path|
    get path, to: "static_pages##{path}"
  end

  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}
  resources :users, only: :show
  
  resources :shops, only: [:index, :show] do
    resources :comments, only: [:create]
  end
  resources :comments, only: :destroy
  resources :likes, only: [:index, :create]
end

app/models/shop.rb
class Shop < ApplicationRecord
  include ImageUploader[:image]
  
  PHONE_REGEX = /\A(((0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1}|[5789]0[-(]?\d{4})[-)]?)|\d{1,4}\-?)\d{4}|0120[-(]?\d{3}[-)]?\d{3})\z/

  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  
  validates :name, presence: true, length: {maximum: 50}
  validates :phone, presence: true, uniqueness: true, format: {with: PHONE_REGEX}
  validates :address, presence: true, length: {maximum: 100}
  validates :area, :station, presence: true, length: {maximum: 20}

  scope :like_num, -> {order(likes_count: :desc)}
  scope :comment_num, -> {order(comments_count: :desc)}

  def like?(user)
    like_users.include?(user)
  end

  def self.search(search)
    if search
      where('name LIKE :search or phone LIKE :search or address LIKE :search or area LIKE :search or station LIKE :search', {search: "%#{search}%"})
    else
      all
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :admin_user?, except: [:index, :show]
  before_action :find_shop, only: [:show, :edit, :update, :destroy]

  MAX_PER_PAGE = 30
  MIN_PER_PAGE = 5
  
  def index
    @shops = Shop.page(params[:page]).per(MAX_PER_PAGE).search(params[:search]).like_num.comment_num
  end

  def show
    @comments = @shop.comments.page(params[:page]).per(MIN_PER_PAGE).desc
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shops_params)
    if @shop.save
      flash[:success] = "店舗の登録に成功しました。"
      redirect_to @shop
    else
      flash[:danger] = "店舗の登録に失敗しました。"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @shop.update_attributes(shops_params)
      flash[:success] = "店舗の編集に成功しました。"
      redirect_to @shop
    else
      flash[:danger] = "店舗の編集に失敗しました。"
      render 'edit'
    end
  end
  
  def destroy
    @shop.destroy
    flash[:success] = "店舗情報を削除しました。"
    redirect_to root_url
  end

  private
  
    def shops_params
      params.require(:shop).permit(
        :name, 
        :phone, 
        :image, 
        :address, 
        :area, 
        :station, 
        :url, 
        :twiiter_url, 
        :facebook_url, 
        :tabelog_url, 
        :google_map_url, 
        :access,
        :business_hour,
        :holiday)
    end

    def find_shop
      @shop = Shop.find(params[:id])
    end

    def admin_user?
      unless user_signed_in? && current_user.admin_flg?
        flash[:danger] = "このページにアクセスする権限がありません。"
        redirect_to root_url
      end
    end
end

app/views/shops/_all_shops.html.slim
.row.my-3.mx-3
  - @shops.each do |shop|
    .col-md-4.mb-3
      .card.mb-3
        = link_to shop_url(shop), class: "shop-card-link" do
          - if shop.image_data
            = image_tag(shop.image[:medium].url, class: "img-fluid mx-auto d-block shop-thumbnail")
          - else
            = image_tag("sample", class: "img-fluid mx-auto d-block", alt: shop.name)
        .card-body.d-flex.justify-content-between
          h5.card-title = link_to shop.name, shop_url(shop), class: "text-dark"
          .row
            span.card-title.fa.fa-heart.like-btn
            span.ml-1 #{shop.likes.size}
            span.card-title.fa.fa-comment.like-btn.ml-2.mr-1
            span.mr-3 #{shop.comments.size}
.row.justify-content-center
  = paginate @shops, theme: 'twitter-bootstrap-4'

app/views/shops/_comments.html.slim
- if @comments.any?
  .container.mt-5
    h4.py-4.mt-2.text-center 『#{@shop.name}』へのコメント
    ol
      - @comments.each do |comment|
        li.list-unstyled.border-top.border-secondary
          - if comment.image_data
            = image_tag(comment.image[:medium].url, class: "img-fluid w-50 mx-auto d-block py-4")
          h5.mt-3.ml-4.font-weight-normal = simple_format(comment.body)
          p.mt-5.text-right
            span 投稿者：
            = link_to comment.user.name, user_path(comment.user.id), class: "mr-2"
            span.mr-2 |
            span.mr-2 #{time_ago_in_words(comment.created_at)}前
            - if comment.user == current_user
              span.mr-2 |
              span = link_to "コメントを削除", comment, method: :delete, data: {confirm: "コメントを削除します。\n本当によろしいですか？"}
    .row.justify-content-center
      = paginate @comments, theme: 'twitter-bootstrap-4'

app/views/shops/_google_map.html.slim
- if @shop.google_map_url
  iframe src="#{Rails.application.config.google_map_base_url}#{@shop.google_map_url}" width="90%" height="450" frameborder="0" style="border:0" allowfullscreen

app/views/shops/_info.html.slim
.py-4
  .container.w-75
    h4.my-3 店舗情報
    table.table.table-hover
      tbody
        tr
          th.text-center 店名
          td = @shop.name
        tr
          th.text-center 住所
          td = @shop.address
        tr
          th.text-center エリア
          td = @shop.area
        tr
          th.text-center 最寄り駅
          td = @shop.station
        tr
          th.text-center 電話番号
          td = link_to @shop.phone, "tel:#{@shop.phone}"
        tr
          th.text-center URL
          td = render 'shop_url'
        tr
          th.text-center 営業時間
          td = simple_format @shop.business_hour, class: "mb-0"
        tr
          th.text-center 定休日
          td = @shop.holiday
        tr
          th.text-center アクセス
          td.embeded-responsive.embeded-responsive-4by3
            = simple_format @shop.access, class: ""
            = render 'google_map'

app/views/shops/_shop_url.html.slim
- if @shop.url
  p.mb-1 = link_to "店舗ホームページ", "#{@shop.url}", target: "blank"
- if @shop.twitter_url
  p.mb-1 = link_to "Twitter", "#{Rails.application.config.twitter_base_url}#{@shop.twitter_url}", target: "blank"
- if @shop.facebook_url
  p.mb-1 = link_to "Facebook", "#{Rails.application.config.facebook_base_url}#{@shop.facebook_url}", target: "blank"
- if @shop.tabelog_url
  p.mb-0 = link_to "食べログ", "#{Rails.application.config.tabelog_base_url}#{@shop.tabelog_url}", target: "blank"

app/views/shops/_top_img.html.slim
.container.my-3
  h1.text-center.py-3.pl-3 #{@shop.name}
  .my-3
    - if @shop.image_data
      = image_tag(@shop.image[:original].url, class: "my-3 img-fluid d-block mx-auto w-50")
    - else 
      = image_tag("sample", class: "my-3 img-fluid d-block mx-auto w-50")

app/views/shops/edit.html.slim
= provide(:title, "店舗編集")
h2.mt-3.mb-2.text-center 店舗編集
.row
  .col-md-6.col-md-offset-3.mx-auto.d-block
    = form_for @shop do |f|
      = f.label :name
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :name, placeholder: "例：Spiceful days", class: "form-control mb-3"
      = f.label :address
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :address, placeholder: "例：東京都千代田区丸の内１丁目", class: "form-control mb-3"
      = f.label :area
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :area, placeholder: "例：東京", class: "form-control mb-3"
      = f.label :station
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :station, placeholder: "例：東京駅", class: "form-control mb-3"
      = f.label :phone
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :phone, placeholder: "例：03-1234-5678", class: "form-control mb-3"
      = f.label :image_data
      .mb-3
        - if @shop.image_data
          = image_tag @shop.image[:medium].url, class: "img-fluid w-75"
        - else
          = image_tag "sample", class: "img-fluid w-75"
      = f.hidden_field :image, value: @shop.cached_image_data
      = f.file_field :image, class:"rounded d-block mb-3"
      = f.label :url
      = f.text_field :url, placeholder: "例：https://www.spicefuldays.com", class: "form-control mb-3"
      = f.label :twitter_url
      span.text-danger （https://twitter.com以降のURLをご記入下さい）
      = f.text_field :twitter_url, placeholder: "例：/spiceful_days", class: "form-control mb-3"
      = f.label :facebook_url
      span.text-danger （https://www.facebook.com以降のURLをご記入下さい）
      = f.text_field :facebook_url, placeholder: "例：/pages/spiceful_days", class: "form-control mb-3"
      = f.label :tabelog_url
      span.text-danger （https://tabelog.com以降のURLをご記入下さい）
      = f.text_field :tabelog_url, placeholder: "例：/tokyo/spiceful_days", class: "form-control mb-3"
      = f.label :google_map_url
      span.text-danger （https://www.google.com/maps以降のURLをご記入下さい）
      = f.text_field :google_map_url, placeholder: "例：/embed?pb=...", class: "form-control mb-3"
      = f.label :business_hour
      = f.text_area :business_hour, placeholder: "例：月〜土：11:30～16:00\n※売切れ次第終了", class: "form-control mb-3 pb-5"
      = f.label :holiday
      = f.text_field :holiday, placeholder: "例：日曜日・祝日", class: "form-control mb-3"
      = f.label :access
      = f.text_area :access, placeholder: "例：東京駅から徒歩1分（100m）、駐車場なし", class: "form-control mb-3 pb-5"
      = f.submit "店舗情報を編集する", class: "btn btn-info btn-lg mt-3 w-100 mb-3"
    .mb-2.text-center
      = link_to "店舗情報を削除", shop_path(@shop), data: {confirm: "店舗を削除するといいね！やコメントが全て消去されます。\n本当によろしいですか？"}, method: :delete
    .mb-4.text-center
      = link_to "戻る", :back

app/views/shops/index.html.slim
= provide(:title, "店舗一覧")
.container
  h2.mt-3.mb-5.text-center 店舗一覧
  = render 'all_shops'

app/views/shops/new.html.slim
= provide(:title, "新規店舗登録")
h2.mt-3.mb-2.text-center 新規店舗登録
.row
  .col-md-6.col-md-offset-3.mx-auto.d-block
    = form_for @shop do |f|
      = f.label :name
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :name, placeholder: "例：Spiceful days", class: "form-control mb-3"
      = f.label :address
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :address, placeholder: "例：東京都千代田区丸の内１丁目", class: "form-control mb-3"
      = f.label :area
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :area, placeholder: "例：東京", class: "form-control mb-3"
      = f.label :station
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :station, placeholder: "例：東京駅", class: "form-control mb-3"
      = f.label :phone
      span.badge.badge-warning.ml-1.px-2.py-1 必須
      = f.text_field :phone, placeholder: "例：03-1234-5678", class: "form-control mb-3"
      = f.label :image_data
      = f.hidden_field :image, value: @shop.cached_image_data
      = f.file_field :image, class:"rounded d-block mb-3"
      = f.label :url
      = f.text_field :url, placeholder: "例：https://www.spicefuldays.com", class: "form-control mb-3"
      = f.label :twitter_url
      span.text-danger （https://twitter.com以降のURLをご記入下さい）
      = f.text_field :twitter_url, placeholder: "例：/spiceful_days", class: "form-control mb-3"
      = f.label :facebook_url
      span.text-danger （https://www.facebook.com以降のURLをご記入下さい）
      = f.text_field :facebook_url, placeholder: "例：/pages/spiceful_days", class: "form-control mb-3"
      = f.label :tabelog_url
      span.text-danger （https://tabelog.com以降のURLをご記入下さい）
      = f.text_field :tabelog_url, placeholder: "例：/tokyo/spiceful_days", class: "form-control mb-3"
      = f.label :google_map_url
      span.text-danger （https://www.google.com/maps以降のURLをご記入下さい）
      = f.text_field :google_map_url, placeholder: "例：/embed?pb=...", class: "form-control mb-3"
      = f.label :business_hour
      = f.text_area :business_hour, placeholder: "例：月〜土：11:30～16:00\n※売切れ次第終了", class: "form-control mb-3 pb-5"
      = f.label :holiday
      = f.text_field :holiday, placeholder: "例：日曜日・祝日", class: "form-control mb-3"
      = f.label :access
      = f.text_area :access, placeholder: "例：東京駅から徒歩1分（100m）、駐車場なし", class: "form-control mb-3 pb-5"
      = f.submit "新規店舗登録", class: "btn btn-primary btn-lg mt-3 w-100 mb-3"

app/views/shops/show.html.slim
= provide(:title, @shop.name)
= render 'top_img'
= render "likes/like"
= render 'comments'
= render 'comments/new'
= render 'info'
- if user_signed_in? && current_user.admin_flg?
	.mb-5.text-center = link_to '店舗を編集する', edit_shop_url(@shop)