config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  %w(about help concept).each do |path|
    get path, to: "static_pages##{path}"
  end

  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}
  resources :users, only: :show
  
  resources :shops, only: [:index, :show] do
    resources :comments, only: [:create]
  end
  resources :comments, only: :destroy
  resources :likes, only: [:index, :create]
end

app/views/layouts/_footer.html.slim
footer.py-1.bg-dark
  .container.text-center
    ul.nav.justify-content-center.mb-3
      li.navbar-item = link_to "ホーム", root_url, class: "nav-link text-light"
      li.navbar-item = link_to "スパイスカレーとは？", about_url, class: "nav-link text-light"
      li.navbar-item = link_to "このサイトについて", concept_url, class: "nav-link text-light"
      li.navbar-item = link_to "よくある質問", help_url, class: "nav-link text-light"
      li.navbar-item = mail_to 'm.fukuzawa0316@gmail.com', "お問い合わせ", subject: 'Spiceful daysに関する問い合わせ', class: "nav-link text-light"
      - if user_signed_in? && current_user.admin_flg?
        li.navbar-item.dropdown
          = link_to "管理メニュー", '#', 'data-toggle': 'dropdown', class: "nav-link dropdown-toggle text-light"
          .dropdown-menu
            = link_to "新規店舗の登録", new_shop_url, class: "dropdown-item"
            = link_to "管理者ページ", rails_admin_url, class: "dropdown-item"
    p
      small.text-light
        | Copyright &copy; Masashi Fukuzawa, All Rights Reserved.

app/views/layouts/_header.html.slim
header.py-2
  = link_to image_tag("top-image", class: "mb-2 w-25 mx-auto d-block"),root_url
nav.navbar.navbar-dark.bg-dark.navbar-expand-md.sticky-top
  .container
    = link_to "Spiceful days", root_url, class: "navbar-brand mr-4" 
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbar-content" 
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbar-content
      ul.navbar-nav.mr-auto
        li.navbar-item.mr-4 = link_to "スパイスカレーとは？", about_url, class: "nav-link"
        li.navbar-item.mr-4 = link_to "店舗一覧", shops_url, class: "nav-link"
        - unless user_signed_in?
          li.navbar-item.mr-4 = link_to "新規登録", new_user_registration_url, class: "nav-link"
          li.navbar-item = link_to "ログイン", new_user_session_url, class: "nav-link"
        - else
          li.navbar-item.mr-4 = link_to "いいね！した店舗", likes_url, class: "nav-link"
          li.navbar-item.dropdown
            = link_to "アカウント", '#', 'data-toggle': 'dropdown', class: "nav-link dropdown-toggle"
            .dropdown-menu
              = link_to "マイページ", user_url(current_user), class: "dropdown-item"
              = link_to "設定", edit_user_registration_url, class: "dropdown-item"
              = link_to "ログアウト", destroy_user_session_url, method: :delete, class: "dropdown-item"
      = form_tag shops_path, method: :get do
        .input-group
          = text_field_tag :search, params[:search], class: "form-control", placeholder: "キーワード"
          span.input-group-btn = submit_tag "検索", name: nil, class: "btn btn-secondary"

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    title = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'
  body
    = render 'layouts/header'
    main
      - flash.each do |message_type, message|
        div class="alert alert-#{bootstrap_class_for(message_type)} text-center" = message
      = yield
      = render 'layouts/footer'